### PR TITLE
Fixing bad results on good pattern

### PR DESCRIPTION
**Pull request by juanjoaquino05**
Changing black loop.

### CODE REVIEW

**Comment by granalberto** [comment]
All tests pass now. That's very good. However, the test covered by the recent fix takes 12ms to complete while the others take less than 1ms. Please elaborate on the reason, analyzing the internals of the language and pointing the lines of the code that cause such bad performance. Also, after the explanation, try to make it more efficient.

**Comment by juanjoaquino05** [comment]
Sure ! test it now

**Comment by granalberto** [comment]
The test is failing again.

**Comment by juanjoaquino05** [comment]
You're right i didnt see the white in my result list. I believe now it is ok.

**Comment by granalberto** [comment]
Yes. It works now. All tests pass.

**Comment by juanjoaquino05** [comment]
Awesome, what about the performance ?

**Comment by granalberto** [comment]
This particular test takes 12ms while the others are less than 1ms. If  you feel in the mood, I'd really like an analysis on that. Even better if you manage to change the implementation and make it faster (this specific use case where all pegs are correct).

**Pull request merged**
